
events {}

http {

    server {

        listen 80;

        location / {
            proxy_pass http://frontend-service:80;
        }

        location /users/ {
            proxy_pass http://user-service:3000/users/;
        }

        location /expenses/ {
            proxy_pass http://expense-service:3000/expenses/;
        }

        location /categories/ {
            proxy_pass http://category-service:3000/categories/;
        }

        location /budgets/ {
            proxy_pass http://budget-service:3000/budgets/;
        }

        location /reports/ {
            proxy_pass http://report-service:3000/reports/;
        }

    }

}
